name: skysqlcli get configurations
synopsis: Retrieve stored service configurations
description: |
  Retrieves one or more custom service configurations owned by the user
usage: skysqlcli get configurations [CONFIGURATION] [flags]
options:
- name: help
  shorthand: h
  default_value: "false"
  usage: help for configurations
- name: limit
  shorthand: l
  default_value: "100"
  usage: |
    Number of records to return. Can be used for paginating results in conjuntion with offset.
inherited_options:
- name: api-key
  usage: Long-lived JWT issued from MariaDB ID
- name: config
  shorthand: c
  usage: config file (default $HOME/.skysqlcli.yaml)
- name: host
  default_value: https://api.skysql.net
  usage: URL for the SkySQL API
- name: mdbid
  default_value: https://id.mariadb.com
  usage: URL for MariaDB ID
see_also:
- skysqlcli get - Query MariaDB SkySQL for resource information
