name: skysqlcli create configuration
synopsis: Create a new configuration
description: Creates a new configuration for user in MariaDB SkySQL.
usage: skysqlcli create configuration [flags]
options:
- name: config-json
  shorthand: j
  default_value: "\n\t\t{\n\t\t\t\"variables\": {\n\t\t\t\t\"interactive_timeout\":
    {\n\t\t\t\t\t\"type\": \"number\",\n\t\t\t\t\t\"value\": \"300\",\n\t\t\t\t\t\"requires_restart\":
    true,\n\t\t\t\t\t\"regex\": \"\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t"
  usage: JSON object containing configuration
- name: help
  shorthand: h
  default_value: "false"
  usage: help for configuration
- name: name
  shorthand: "n"
  default_value: HA
  usage: Name used to identify the configuration
- name: topology
  shorthand: t
  default_value: Read Scalable Transactions
  usage: Configuration topology to select
inherited_options:
- name: api-key
  usage: Long-lived JWT issued from MariaDB ID
- name: config
  shorthand: c
  usage: config file (default $HOME/.skysqlcli.yaml)
- name: host
  default_value: https://api.dev.gcp.mariadb.net
  usage: URL for the SkySQL API
- name: mdbid
  default_value: https://id-dev.mariadb.com
  usage: URL for MariaDB ID
see_also:
- skysqlcli create - Create a resource in MariaDB SkySQL
