name: skysqlcli update configuration
synopsis: Update a configuration
description: Updates a configuration for user in MariaDB SkySQL.
usage: skysqlcli update configuration [CONFIGURATION] [flags]
options:
- name: config-json
  shorthand: j
  usage: JSON object containing configuration
- name: help
  shorthand: h
  default_value: "false"
  usage: help for configuration
- name: name
  shorthand: "n"
  usage: Name used to identify the configuration
inherited_options:
- name: api-key
  usage: Long-lived JWT issued from MariaDB ID
- name: config
  shorthand: c
  usage: config file (default $HOME/.skysqlcli.yaml)
- name: host
  default_value: https://api.skysql.net
  usage: URL for the SkySQL API
- name: mdbid
  default_value: https://id.mariadb.com
  usage: URL for MariaDB ID
see_also:
- skysqlcli update - Update a resource in MariaDB SkySQL
