.nh
.TH "SkySQL CLI Client" "3" "Jan 2022" "MariaDB Corporation" ""

.SH NAME
.PP
skysqlcli\-delete\-configuration \- Delete a service configuration


.SH SYNOPSIS
.PP
\fBskysqlcli delete configuration [CONFIGURATION] [flags]\fP


.SH DESCRIPTION
.PP
Deletes a service configuration for user in MariaDB SkySQL.


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for configuration


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-key\fP=""
	Long\-lived JWT issued from MariaDB ID

.PP
\fB\-c\fP, \fB\-\-config\fP=""
	config file (default $HOME/.skysqlcli.yaml)

.PP
\fB\-\-host\fP="https://api.dev.gcp.mariadb.net"
	URL for the SkySQL API

.PP
\fB\-\-mdbid\fP="https://id\-dev.mariadb.com"
	URL for MariaDB ID


.SH SEE ALSO
.PP
\fBskysqlcli\-delete(3)\fP
