.nh
.TH "SkySQL CLI Client" "3" "Nov 2021" "MariaDB Corporation" ""

.SH NAME
.PP
skysqlcli\-get\-credentials \- Retrieve default service credentials


.SH SYNOPSIS
.PP
\fBskysqlcli get credentials [SERVICE] [flags]\fP


.SH DESCRIPTION
.PP
Queries for default credentials configured for a service. Specify a service using the service id (e.g. db00000000)


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for credentials


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-key\fP=""
	Long\-lived JWT issued from MariaDB ID

.PP
\fB\-c\fP, \fB\-\-config\fP=""
	config file (default $HOME/.skysqlcli.yaml)

.PP
\fB\-\-host\fP="https://api.dev.gcp.mariadb.net"
	URL for the SkySQL API

.PP
\fB\-l\fP, \fB\-\-limit\fP=10
	Number of records to return

.PP
\fB\-\-mdbid\fP="https://id\-dev.mariadb.com"
	URL for MariaDB ID


.SH SEE ALSO
.PP
\fBskysqlcli\-get(3)\fP
