.nh
.TH "SkySQL CLI Client" "3" "Nov 2021" "MariaDB Corporation" ""

.SH NAME
.PP
skysqlcli\-get\-configurations \- Retrieve stored service configurations


.SH SYNOPSIS
.PP
\fBskysqlcli get configurations [CONFIGURATION] [flags]\fP


.SH DESCRIPTION
.PP
Retrieves one or more custom service configurations owned by the user


.SH OPTIONS
.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for configurations


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-key\fP=""
	Long\-lived JWT issued from MariaDB ID

.PP
\fB\-c\fP, \fB\-\-config\fP=""
	config file (default $HOME/.skysqlcli.yaml)

.PP
\fB\-\-host\fP="https://api.dev.gcp.mariadb.net"
	URL for the SkySQL API

.PP
\fB\-l\fP, \fB\-\-limit\fP=10
	Number of records to return

.PP
\fB\-\-mdbid\fP="https://id\-dev.mariadb.com"
	URL for MariaDB ID


.SH SEE ALSO
.PP
\fBskysqlcli\-get(3)\fP
