.nh
.TH "SkySQL CLI Client" "3" "Nov 2021" "MariaDB Corporation" ""

.SH NAME
.PP
skysqlcli\-create\-allowed\-address \- Add a new allowed address to a service


.SH SYNOPSIS
.PP
\fBskysqlcli create allowed\-address [SERVICE] [IP\-ADDRESS] [flags]\fP


.SH DESCRIPTION
.PP
Adds a new allowed address for service in MariaDB SkySQL.


.SH OPTIONS
.PP
\fB\-\-comment\fP=""
	Additional comment to help identify address

.PP
\fB\-h\fP, \fB\-\-help\fP[=false]
	help for allowed\-address


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.PP
\fB\-\-api\-key\fP=""
	Long\-lived JWT issued from MariaDB ID

.PP
\fB\-c\fP, \fB\-\-config\fP=""
	config file (default $HOME/.skysqlcli.yaml)

.PP
\fB\-\-host\fP="https://api.dev.gcp.mariadb.net"
	URL for the SkySQL API

.PP
\fB\-\-mdbid\fP="https://id\-dev.mariadb.com"
	URL for MariaDB ID


.SH SEE ALSO
.PP
\fBskysqlcli\-create(3)\fP
